---
title: "Group Assignment"
output:
  html_document:
    df_print: paged
---

Load the libraries and the SA data 

```{r}
## Load the libs
# EDA
library(DataExplorer)
library(ggplot2)
library(plotly)
# Core 
library(tidyverse)
library(timetk)
library(lubridate)
# Accuracy
library(yardstick)
# Anomaly
library(anomalize)
# 1.0 Read DATA -----
# consumption ----
sa_cons <- read.csv("sa/totaldemand_sa.csv")
## Convert Dt
sa_cons<-sa_cons%>%mutate(DATETIME = ymd_hms(DATETIME))

# temperature ----

temp_sa<-read.csv("sa/temprature_sa.csv")
## convert Dt
temp_sa<- temp_sa %>% mutate(DATETIME = ymd_hms(DATETIME))

# forecasted ----
forcst_sa <- read.csv("sa/forecastdemand_sa.csv") 
forcst_sa<- forcst_sa%>% mutate(DATETIME = ymd_hms(DATETIME),LASTCHANGED = ymd_hms(LASTCHANGED))
```

Plot the time series

```{r}
sa_cons%>%plot_time_series(.date_var = DATETIME,.value = TOTALDEMAND,.interactive = F)

```
ACF and PACF

```{r}
sa_cons%>%filter(DATETIME>="2015-01-01")%>%
  plot_acf_diagnostics(.date_var = DATETIME,.value = TOTALDEMAND,.lags = 0:17520)
```
Plot seasonal diagnostics

```{r}
sa_cons%>%filter(DATETIME>="2015-01-01")%>%
  plot_seasonal_diagnostics(DATETIME, TOTALDEMAND,.feature_set = c("quarter","month.lbl"),.y_lab = "DEMAND")
```
```{r}
sa_cons %>%filter(DATETIME>="2015-01-01")%>%
  plot_seasonal_diagnostics(DATETIME, TOTALDEMAND,.feature_set = c("hour","wday.lbl","week"),.y_lab = "DEMAND")

```